---
- name: JSON Query
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get JSON file content
      ansible.builtin.set_fact:
        jsondata: "{{ lookup('file','files/file.json') | from_json }}"

    - name: "Query partial JSON content, e.g.: Business Card"
      ansible.builtin.debug:
        msg: "{{ jsondata | community.general.json_query(some_data) }}"
      vars:
        some_data: "[*].{Name: name, Email: email, Phone: phone, CompanyName: company.name, WebSite: website, City: address.city}"
...
