---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
- name: Custom Facts
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Collect local ansible facts
      ansible.builtin.setup:
        filter:
          - 'ansible_local'
        fact_path: "{{ playbook_dir }}/facts.d"

    - name: Custom facts
      ansible.builtin.debug:
        msg:
          - "{{ ansible_local.ini_preference.general }}"
          - "{{ ansible_local.json_preference.general }}"
          - "{{ ansible_local.python_fact }}"
          - "{{ ansible_local.date_time }}"
          - "{{ ansible_local.run_docker_command }}"
      #delegate_to: ""
      #delegate_facts: true
...
