---
- name: Examples
  hosts: ansible_vm
  become: false
  gather_facts: false

  tasks:
    - name: test
      ansible.builtin.debug:
        msg:
          - "Hello, I am running on {{ inventory_hostname }}!"
...
