---
- name: Host Grouping
  hosts: docker_host
  become: false
  gather_facts: false

  vars:
    ignore_groups:
      - webservers
      - "*_server"
      - ungrouped

  tasks:
    - name: Show hostname in inventory
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }}"

    - name: List all groups in inventory
      ansible.builtin.debug:
        msg:
          - "{{ groups.keys() | list }}"

    - name: List all hosts in inventory
      ansible.builtin.debug:
        msg:
          - "{{ query('inventory_hostnames', 'all') }}"

    - name: List all hosts in inventory except for some groups
      ansible.builtin.debug:
        msg:
          - "{{ query('inventory_hostnames', 'all') }}"
          - "{{ query('inventory_hostnames', 'all: !webservers !*_server !ungrouped') }}"

    - name: List all hosts in a specific group
      ansible.builtin.debug:
        msg:
          - "{{ query('inventory_hostnames', 'external') }}"
          - "{{ query('inventory_hostnames', 'linux_all: !*_server') }}"
          

    - name: Create group list and removing ignores
      ansible.builtin.set_fact:
        target_groups: "{{ target_groups|default('all:') + ' !' + item }}"
      loop: "{{ ignore_groups }}"

    - name: List all hosts in inventory except for some groups via variable
      ansible.builtin.debug:
        msg:
          - "{{ query('inventory_hostnames', target_groups|default('all')) }}"
...
