---
- name: Host Grouping with exclusion 1
  hosts: linux_server !webservers !docker_host
  become: false
  gather_facts: false

  tasks:
    - name: Show hostname in inventory
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }}"


- name: Host Grouping with exclusion 2
  hosts:
    linux_server
    !webservers
    !docker_host
  become: false
  gather_facts: false

  tasks:
    - name: Show hostname in inventory
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }}"
...
