---
- name: Host Grouping
  hosts: linux_server !webservers !docker_host
  become: false
  gather_facts: false

  tasks:
    - name: Show hostname in inventory
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }}"
...
