---
all:
  children:
    internal:
      children:
        ansible_vm:
          hosts:
            localhost:
              ansible_connection: local
              host_test_var: test
          vars:
            group_test_var: test

        linux_all:
          children:
            linux_clients:
              hosts:
                client1:
                client2:
            linux_server:
              hosts:
                server1:
              children:
                docker_host:
                  hosts:
                    docker_linux:
                webservers:
                  hosts:
                    www[01:50:2].example.com:

        windows_all:
          children:
            windows_clients:
              hosts:
                client1:
            windows_server:
              hosts:
                server1:
              children:
                docker_host:
                  hosts:
                    docker_windows:

    external:
      hosts:
        github.com:
          ansible_host: github.com
          ansible_user: git
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/<your_ssh_key>

hosts:
  ungrouped_host:
...
