---
all:
  children:
    internal:
      children:
        ansible_vm:
          hosts:
            localhost:
              ansible_connection: local
              host_test_var: test
          vars:
            group_test_var: test

        linux_all:
          children:
            linux_clients:
              hosts:
                linux_client1:
                linux_client2:
            linux_server:
              hosts:
                linux_server1:
              children:
                docker_host:  # Beware, hosts in groups with the same name are grouped together, when the group is used in a playbook
                  hosts:
                    linux_docker:
                webservers:
                  hosts:
                    www[01:06:2].example.com: # Contains hosts starting with www01 to www06 with (optional) step 2

        windows_all:
          children:
            windows_clients:
              hosts:
                windows_client1:
            windows_server:
              hosts:
                windows_server1:
              children:
                docker_host:  # Beware, hosts in groups with the same name are grouped together, when the group is used in a playbook
                  hosts:
                    windows_docker:

    external:
      hosts:
        github.com:
          ansible_host: github.com
          ansible_user: git
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/<your_ssh_key>

clients_all:
  children:
    linux_clients:
    windows_clients:

server_all:
  children:
    linux_server:
    windows_server:

hosts:
  ungrouped_host:
...
