---
- name: Basic task
  ansible.builtin.debug:
    msg:
      - "I am a task within a role"

- name: Template
  when: false
  ansible.builtin.template:
    src: example.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
...
